adminUser: admin
adminPassword: admin

grafana.ini:
  security:
    disable_initial_admin_change_password: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service
        jsonData:
          maxLines: 1000

# Optional: Recommended hardening settings
users:
  allowSignUp: false

auth:
  anonymous:
    enabled: false
